# Site settings
name: Less Is More
email: wanghao27@163.com
author: Wang Hao
url: http://lunasi27.github.io
resume_site: ''
github: https://github.com/LessIsMore/
baseurl: ''
description: Actually, less is more!
meta_description: 王昊的个人博客;非典型性程序员;证券市场业余韭菜;币圈非资深投资者;
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lunasi27

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

